version: "3.3"
services:
  php:
    build:
      context: ../
      dockerfile: docker/containers/apache-php/Dockerfile
    volumes:
      - ../:/var/www/project:delegated
    ports:
      - "80:8080"
  db:
    build:
      context: ../
      dockerfile: docker/containers/database/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root


